CREATE TABLE IF NOT EXISTS `lab_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(500) NOT NULL COMMENT '活动标题',
  `summary` varchar(1000) DEFAULT NULL COMMENT '活动摘要',
  `event_time` date NOT NULL COMMENT '活动日期',
  `content` longtext COMMENT '活动内容（富文本）',
  `tag` varchar(100) DEFAULT NULL COMMENT '活动标签',
  `owner_user_id` bigint NOT NULL COMMENT '活动负责人（创建者）',
  `published` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否发布',
  `creator_id` bigint DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater_id` bigint DEFAULT NULL COMMENT '更新者ID',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_event_time` (`event_time`),
  KEY `idx_event_owner` (`owner_user_id`),
  KEY `idx_event_published_time` (`published`,`event_time`),
  KEY `idx_event_tag` (`tag`),
  CONSTRAINT `fk_event_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `lab_user` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='活动表';

CREATE TABLE IF NOT EXISTS `lab_event_author` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `event_id` bigint NOT NULL COMMENT '活动ID',
  `user_id` bigint DEFAULT NULL COMMENT '内部作者user_id，NULL表示外部作者',
  `name` varchar(100) DEFAULT NULL COMMENT '作者姓名',
  `name_en` varchar(100) DEFAULT NULL COMMENT '作者英文名',
  `affiliation` varchar(300) DEFAULT NULL COMMENT '作者单位',
  `author_order` int NOT NULL COMMENT '作者顺序（>=1）',
  `is_corresponding` tinyint(1) DEFAULT '0' COMMENT '是否通讯作者',
  `role` varchar(100) DEFAULT NULL COMMENT '作者角色',
  `visible` tinyint(1) DEFAULT '1' COMMENT '是否展示',
  `creator_id` bigint DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater_id` bigint DEFAULT NULL COMMENT '更新者ID',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_event_author_order` (`event_id`,`author_order`,`deleted`),
  UNIQUE KEY `uniq_event_author_user` (`event_id`,`user_id`),
  KEY `idx_event_author_event` (`event_id`),
  KEY `idx_event_author_user` (`user_id`),
  CONSTRAINT `fk_event_author_event` FOREIGN KEY (`event_id`) REFERENCES `lab_event` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_event_author_order_positive` CHECK ((`author_order` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='活动作者表';
